In [31]:
import pandas as pd 
import numpy as np 

df_vendas = pd.read_csv("vendas_tech.csv", low_memory= False) 
# encoding - caractere expecial 
# sep - define o separador ds infromações 
# low_memory = False -> carregar a tabela inteira 
display(df_vendas)
df_gerente = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerente)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [32]:
# inspeção 
display(df_vendas)
display(df_vendas.head(15))
display(df_vendas.tail(15)) 
display(df_vendas.sample(15))
display(df_vendas.info())
display(df_vendas.shape)
display(df_vendas.describe())
display(list(df_vendas.columns))

# head -> mostra as 5 priemrias linhas 
# tail -> mostra as 5 ultimas linhas
# sample -> mostra 5 linhas aleatorias do seu banco de dados
# info -> mostra o resumo da sua base de dados, como ripo de dados, colunas e linhas
# shape -> mostra a quantidade de linhas e tabelas 
# describe -> mostra dados de estatisticas sobre as tabelas numéricas
# colums -> mostra as colunas em formato de lista
# () -> passa quantas linhas quer ver

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN
10,11,2023-06-28,RIO DE JANEIRO,Smartphone Samsung,2200.0,1,Cliente_3253,NaN
11,12,2024-01-29,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_586,NaN
12,13,2024-06-25,Recife,Smartphone Samsung,2200.0,1,Cliente_4301,NaN
13,14,2023-04-13,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_22985,NaN
14,15,2023-06-23,Curitiba,Cabo HDMI,40.0,1,Cliente_27383,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100085,90626,2023-01-25,Porto Alegre,iPhone 14,5500.0,1,Cliente_14913,NaN
100086,18337,2023-10-04,Curitiba,Notebook Dell,3500.0,2,Cliente_16605,NaN
100087,81502,2024-06-14,São Paulo,Notebook HP,3200.0,1,Cliente_19663,NaN
100088,92089,2024-06-12,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_21537,NaN
100089,169,2023-10-10,Recife,Mouse Gamer,120.0,3,Cliente_4407,NaN
100090,15752,2023-03-20,Curitiba,"Monitor 27""",1200.0,1,Cliente_356,NaN
100091,4801,2023-10-29,São Paulo,Smartphone Samsung,2200.0,1,Cliente_5799,NaN
100092,89541,2023-09-01,Porto Alegre,"Monitor 27""",1200.0,1,Cliente_24144,NaN
100093,77528,2024-03-30,São Paulo,"Monitor 27""",1200.0,3,Cliente_5144,NaN
100094,32853,2024-04-10,Salvador,Smartphone Samsung,2200.0,2,Cliente_29799,NaN
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
96320,96321,2024-07-31,Rio de Janeiro,"Monitor 27""",1200.0,1,Cliente_7656,NaN
17578,17579,2024-01-15,Belo Horizonte,Cabo HDMI,40.0,5,Cliente_9326,NaN
45181,45182,2023-07-23,Belo Horizonte,iPhone 14,5500.0,1,Cliente_14705,NaN
32870,32871,2023-03-24,São Paulo,Smartphone Samsung,2200.0,2,Cliente_4648,NaN
84903,84904,2023-10-28,Curitiba,Mouse Gamer,120.0,1,Cliente_26526,NaN
16618,16619,2024-07-10,Porto Alegre,Smartphone Samsung,2200.0,1,Cliente_17187,NaN
25186,25187,2024-04-30,Belo Horizonte,Notebook HP,3200.0,5,Cliente_16701,NaN
27193,27194,2024-02-18,Porto Alegre,Smartphone Samsung,2200.0,1,Cliente_3207,NaN
41339,41340,2024-08-13,Rio de Janeiro,Notebook HP,3200.0,2,Cliente_4587,NaN
67720,67721,2024-10-02,Salvador,Smartphone Samsung,2200.0,1,Cliente_9588,NaN
55108,55109,2024-04-21,Salvador,Notebook Dell,3500.0,2,Cliente_3690,NaN
5886,5887,2024-09-03,Salvador,Notebook Dell,3500.0,1,Cliente_6073,NaN
37285,37286,2023-08-26,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_593,NaN
90970,90971,2024-11-14,Salvador,Teclado Mecânico,250.0,1,Cliente_13071,NaN
10217,10218,2023-06-04,Curitiba,Notebook Dell,3500.0,2,Cliente_6392,NaN

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

(100100, 8)

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

In [33]:
# tratamentos 
display(df_vendas[['Loja', 'Produto','Qtd']])
# colunas
# df_analise = df_vendas[['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd', 'Cliente']]
# display(df_vendas) -> jeito mais dificl -> Selecionar cada tabela e não adicionar a não desejada

df_analise = df_vendas.drop(columns=['Data_Base'])
display(df_analise)
# drop -> vai excluir a tabela desejada -> jeito facil 


# nulos 
# df_analise = df_analise.dropna()
# display(df_analise) -> vai apagar as linhas que tiverem qualquer valor nulo

df_analise['Loja'] = df_analise['Loja'].fillna("Online")

# fillna -> vai preencher as linhas vazias com o parametro passado pelo parenteses "Online"

display(df_analise)

# tipos de dados 

df_analise['Data'] = pd.to_datetime(df_analise['Data'], format="%Y-%m-%d")

# pd.to_datetime -> vai converter o tipo de dado, nesse exemplo de str -> datetime 
# format -> passa o estilo da data --- |%Y -> ano | %m -> mês |  %d -> dia|

# Padronização 
df_analise['Loja'] = df_analise['Loja'].str.strip() #Remove os espaços em branco
df_analise['Loja'] = df_analise['Loja'].str.title() #Deixa a primeira letra de cada palavra maiúscula



# duplicatas
df_analise = df_analise.drop_duplicates(subset=['ID_Pedido']) # drop_duplicates -> Tira valores duplicados | subset -> seleciona o parametro de excluzão, ou seja, "Se possuir Id's iguais, exclua"

# Exibição da base de dados formatadas 

display(df_analise)
display(df_analise.info())
display(df_analise.shape)

                  Loja             Produto  Qtd
0            São Paulo         Mouse Gamer    1
1       Belo Horizonte           iPhone 14    1
2                  NaN         Monitor 27"    1
3       RIO DE JANEIRO         Mouse Gamer    2
4       Rio de Janeiro  Smartphone Samsung    1
...                ...                 ...  ...
100095    Porto Alegre           iPhone 14    1
100096    Porto Alegre       Notebook Dell    2
100097  Belo Horizonte  Smartphone Samsung    2
100098        Salvador           iPhone 14    2
100099      São Paulo          Notebook HP    2

[100100 rows x 3 columns]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

(100000, 7)

In [37]:
#Criar novas colunas

#Faturamento
df_analise['Faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario'] #Multiplicação entre as tabelas

#Forma de venda 
df_analise['Forma_De_Venda'] = np.where(df_analise['Loja']=='Online', 'Online', 'Presencial')
#np.where() -> como se fosse um if  ---->  (    valor,             se verdaderio,   se falso)

#Região
display(list(df_analise['Loja'].unique()))

dic_regioes = {
    'São Paulo': 'Sudeste',
 'Belo Horizonte': 'Sudeste',
 'Online': 'Online',
 'Rio De Janeiro': 'Sudeste',
 'Salvador': 'Nordeste',
 'Recife': 'Nordeste',
 'Curitiba': 'Sul',
 'Porto Alegre': 'Sul'
}

df_analise['Regiao'] = df_analise['Loja'].map(dic_regioes)

#map -> ele substitui o valor da coluna conforme o parametro passado, nesse caso, se o nome da loja for igual a São Paulo (key), tera seu valor como Sudeste (value)




display(df_analise)

display(df_analise.isna().sum())

['São Paulo',
 'Belo Horizonte',
 'Online',
 'Rio De Janeiro',
 'Salvador',
 'Recife',
 'Curitiba',
 'Porto Alegre']

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_De_Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_De_Venda    0
Regiao            0
dtype: int64